### ISSUE TITLE
Helm chart forces legacy autoscaling manifest

### ISSUE THREAD

**Issue by eahrend** [harness/delegate-helm-chart#79]
Hey,

I'm using the latest version of the helm chart, and it's attempting to use the legacy version of autoscaler. Here is my values.yaml:
```YAML
delegateName: %s
accountId: %s
managerEndpoint: https://app.harness.io/gratis
delegateDockerImage: harness/delegate:24.01.82108
replicas: 2
cpu: 2
memory: 4096
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
upgrader:
  enabled: false
delegateToken: %s
tags: %s
```

The version of K8S that I'm on is: 
1.26.6-gke.1700
